[phases.setup]
nixPkgs = ["python311", "tesseract"]

[phases.install]
cmds = [
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python3 backend/app.py"