[phases.setup]
nixPkgs = [
    "python311", 
    "tesseract", 
    "pkg-config",
    "libffi",
    "openssl",
    "gcc",
    "glib",
    "glibc"
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python backend/app.py"