[phases.setup]
nixPkgs = [
    "python311", 
    "python311Packages.pip",
    "tesseract",
    "pkg-config",
    "libffi",
    "openssl",
    "gcc"
]

[phases.install]
cmds = ["python3 -m pip install -r backend/requirements.txt"]

[start]
cmd = "python backend/app.py"