[phases.setup]
nixPkgs = ["python311", "tesseract"]
providers = ["...", "python"]
[phases.install]
nixPkgs = ["...","flask","flask_cors"]
aptPkgs = ["...","pytesseract"]
aptPkgs = ["...","opencv"]

[start]
cmd = "python backend/app.py"